modLoader = "lowcodefml"
loaderVersion = "[25,)"
license = "GPL-3.0"

[[mods]]
modId = "prometheus-lunar"
version = "0.0.0" # not to be updated since the forge folks like to enforce strict versioning </3
displayName = "Prometheus"
description = "${project.description}"
logoFile = "assets/prometheus/icon.png"
features = { java_version = "[8,)" }
authors = ["dxxxxy", "Cootshk"]